version: "3.9"

services:
  backend:
    build: .
    container_name: snap_backend
    restart: always
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./:/usr/src/app

  dbgate:
    image: dbgate/dbgate
    container_name: snap_db_viewer
    restart: always
    ports:
      - "8083:3000"         # Open http://localhost:8083
    environment:
      CONNECTIONS_SOURCE: "localjson"
